export {
  TEACHER_AGENDA_LEGACY_PATH,
  TEACHER_CONTROL_CENTER_LEGACY_PATHS,
  TEACHER_FINANCE_LEGACY_PATH,
  TEACHER_PLANNING_LEGACY_PATH,
  TEACHER_PRIVATE_SIGNUP_LEGACY_PATH,
  TEACHER_STUDENTS_LEGACY_PATH,
} from "@kidario/shared/routes/frontend";
