export {
  TEACHER_AGENDA_PATH,
  TEACHER_CONTROL_CENTER_PATH,
  TEACHER_FINANCE_PATH,
  TEACHER_LESSON_CLOSURE_PATH,
  TEACHER_PLANNING_PATH,
  TEACHER_PRIVATE_SIGNUP_PATH,
  TEACHER_STUDENTS_PATH,
  buildTeacherLessonClosurePath,
} from "@kidario/shared/routes/frontend";
